version: 3

sources:
  - name: "{{ env_var('DBT_ENV_CUSTOM_ENV_CLICKHOUSE_USR') }}"
    database: "{{ env_var('DBT_ENV_CUSTOM_ENV_SCHEMA') }}"
    tables: 
      - name: "{{ env_var('DBT_ENV_CUSTOM_ENV_CLICKHOUSE_TABLE') }}"