de_project_airflow:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('DBT_ENV_CUSTOM_ENV_SCHEMA') }}"
      host: "{{ env_var('HOST_CLICKHOUSE') }}"
      port: 8123
      user: "{{ env_var('DBT_ENV_CUSTOM_ENV_CLICKHOUSE_USR') }}"
      password: "{{ env_var('DBT_ENV_SECRET_CLICKHOUSE_PW') }}"
      secure: False
  